spring.application.name=SpendSight

#info general de la BD
spring.datasource.url=jdbc:h2:mem:SpendSight_db
spring.datasource.username=sa
spring.datasource.password=

#activo el h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#activo el JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
